spring.application.name=alerta-vecinal
spring.datasource.url=jdbc:mysql://localhost:3306/alerta_vecinal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=hectorpalacios
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
